### ISSUE TITLE
读取博客文章数目不全

### ISSUE THREAD

**Issue by silenceeeeee** [junyiz/dature#10]
全部博客文章共有1000+条，但目前只能抓取前5条.
![image](https://user-images.githubusercontent.com/73045930/168259233-70c1f136-b501-4e6e-beaa-32e91b885a7d.png)
<img width="720" alt="image" src="https://user-images.githubusercontent.com/73045930/168259657-97cb2ccd-a2d1-4eb6-8ce9-9a545efbf979.png">

**Comment by junyiz** [comment]
可能有啥 bug 吧？但新浪博客改为登录才能查看后，调试代码就需要一个账号或 cookie 了，你若愿意的话，可以把你的账号或 cookie 发我邮箱(junyime@qq.com)，我看到时会看看

**Comment by silenceeeeee** [comment]
已发。感觉这个可能和跨度时间有关系，我5.9第一次抓取的时候是能抓到10条的，昨天5.13就只能抓5条，刚刚试了下现在只有4条了。

**Comment by junyiz** [comment]
已经修复了，请下载 0.3.4 版上试试

**Comment by silenceeeeee** [comment]
已更新至0.3.4，目前还是不行，现在只能获取前两篇了。可能是cookie的问题，我试了一下加不加cookie读取到结果的是一样的。
<img width="722" alt="image" src="https://user-images.githubusercontent.com/73045930/168456765-211ee26e-9dce-4117-8f67-dda144dd1dd4.png">
![image](https://user-images.githubusercontent.com/73045930/168456783-478601b6-e7ee-4f8d-a771-d203113f9cc4.png)

**Comment by junyiz** [comment]
我自己试，已经可以了

**Comment by silenceeeeee** [comment]
那...可能是我windows系统的问题？我再去借个机器看下。

**Comment by silenceeeeee** [comment]
破案了，windows里面命令行-c后面的cookies应该打双引号，我按readme里面一直打的单引号。不好意思麻烦你了，现在已经可以正常读取了。
