### ISSUE TITLE
自己的博客无法导出

### ISSUE THREAD

**Issue by whalucard** [junyiz/dature#11]
执行命令后，我自己的博客无法导出
能识别到我博客的名字，但是导出0条
然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。
可能新浪博客快要停运了。
关闭这个权限了？

**Comment by junyiz** [comment]
> 执行命令后，我自己的博客无法导出 能识别到我博客的名字，但是导出0条 然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。 可能新浪博客快要停运了。 关闭这个权限了？

操作正确的话，本人的博客能导出的

**Comment by whalucard** [comment]
> > 执行命令后，我自己的博客无法导出 能识别到我博客的名字，但是导出0条 然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。 可能新浪博客快要停运了。 关闭这个权限了？
> 
> 操作正确的话，本人的博客能导出的

dature -u 1263917762 -c "xxxxxx"

# xxxxxx 为 cookie

**Comment by whalucard** [comment]
> > 执行命令后，我自己的博客无法导出 能识别到我博客的名字，但是导出0条 然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。 可能新浪博客快要停运了。 关闭这个权限了？
> 
> 操作正确的话，本人的博客能导出的

dature -u 1263917762 -c "xxxxxx"
xxxxxx 为 cookie

**Comment by whalucard** [comment]
> > 执行命令后，我自己的博客无法导出 能识别到我博客的名字，但是导出0条 然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。 可能新浪博客快要停运了。 关闭这个权限了？
> 
> 操作正确的话，本人的博客能导出的

dature -u 1263917762 -c "xxxxxx"
xxxxxx 为 cookie   大佬问下这个cookie是怎么获取呢

**Comment by whalucard** [comment]
> > 执行命令后，我自己的博客无法导出 能识别到我博客的名字，但是导出0条 然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。 可能新浪博客快要停运了。 关闭这个权限了？
> 
> 操作正确的话，本人的博客能导出的
我尝试导了一个可以正常打开的别人的博客是可以导出来的。。。所以感觉我的操作应该没问题。。

**Comment by junyiz** [comment]
> 

看文档

**Comment by junyiz** [comment]
> > > 执行命令后，我自己的博客无法导出 能识别到我博客的名字，但是导出0条 然后发现点击任何人的博客都提示：系统维护中，博文仅作者可见。登陆后可查看本人文章。 可能新浪博客快要停运了。 关闭这个权限了？
> > 
> > 
> > 操作正确的话，本人的博客能导出的
> 
> dature -u 1263917762 -c "xxxxxx" xxxxxx 为 cookie 大佬问下这个cookie是怎么获取呢

看文档
