### ISSUE TITLE
恳请您的帮助！！

### ISSUE THREAD

**Issue by guozijing-zjk** [junyiz/dature#12]
❗当我用您的程序爬取博文到一定数量时，它就这样报错了。❗
![1](https://user-images.githubusercontent.com/26113017/170494881-ab757722-a556-4a1a-84e2-9065e4a75512.png)

- ❌我甚至用Linux笔记本跑了一下，也在一定页数出现了相同的错误（另外一台电脑，不是虚拟机）
- ❌不管是Windows10还是Linux文件夹权限都是对的，用管理员方式运行也不行😥
- ❌我删除了node_modules文件夹好几遍重新安装也没用😭
- ❌自己处理问题的能力有限，Google&bing&百度都找过问题的解决办法，但是我自己还是不会解决😥
- 🙏非常希望您可以帮助我解决这个问题，甚至💰有偿💰也愿意，我想帮我姥姥把她写了十来年的文章导出来。🙏
- 🎄等待您在百忙之中的回复的，这个问题困扰我两个星期了😢🎄
- ❤爱您

**Comment by guozijing-zjk** [comment]
💡💡💡💡💡

**Comment by guozijing-zjk** [comment]
💡💡💡💡💡💡💡

**Comment by junyiz** [comment]
> 💡💡💡💡💡💡💡

改了一下，不确定一定改对了，因为没有账号测试，你先再试一下吧

**Comment by guozijing-zjk** [comment]
感谢大佬，我晚上试一哈

**Comment by guozijing-zjk** [comment]
Ohhhhhhhh太感谢了大佬，5700个文章都导出了!学生党的我等攒上钱请你喝咖啡☕️😀开源拯救世界!
