### ISSUE TITLE
备份的图片，不是原始大图

### ISSUE THREAD

**Issue by leoncin** [junyiz/dature#13]
从Html获取的图片地址是类似： http://s15.sinaimg.cn/mw690/0022E8QHzy7WvtCeEUe4e&690
可以换为： http://s15.sinaimg.cn/orignal/0022E8QHzy7WvtCeEUe4e

目录的： mw690 替换为 orignal
最后的 &690 删除

这样就完美了。

**Comment by junyiz** [comment]
已支持

**Comment by leoncin** [comment]
赞！
