### ISSUE TITLE
能否支持备份私密博文分类下的内容？

### ISSUE THREAD

**Issue by leiddev** [junyiz/dature#15]
很多以前正常的博文被新浪转为私密博文了，请问能否支持备份这部分的内容？

**Comment by junyiz** [comment]
> 

你愿意贡献一个有私密博文的账号吗

**Comment by junyiz** [comment]
> 很多以前正常的博文被新浪转为私密博文了，请问能否支持备份这部分的内容？

你愿意贡献一个有私密博文的账号吗

**Comment by leiddev** [comment]
尝试了一下，将sina.js里面的第19行的url改为
http://control.blog.sina.com.cn/blog_rebuild/blog/controllers/articlelist.php?uid=${uid}&p=${i}&status=5
就可以抓取到私密博文，后面流程都正常，但是要带上这个页面的cookies才行。
如果将url改为
http://control.blog.sina.com.cn/blog_rebuild/blog/controllers/articlelist.php?uid=${uid}&p=${i}&status=1
可以抓取全部可见博文，效果和用 http://blog.sina.com.cn/s/articlelist_${uid}_0_${i}.html 这个url一样，但是cookies可以用和私密博文列表页面一样的cookis，这样用这一个cookies就可以把可见博文和私密博文都抓取下来。

**Comment by junyiz** [comment]
已支持

**Comment by leiddev** [comment]
感谢，不过可能误解我的意思了，status=5才能获取到私密博文。要抓取这个URL下的列表才能获取到私密博文。

**Comment by junyiz** [comment]
> 感谢，不过可能误解我的意思了，status=5才能获取到私密博文。要抓取这个URL下的列表才能获取到私密博文。

我因为没账号，所以没法测试，你能否提个 PR ？
