### ISSUE TITLE
这该怎么办呢

### ISSUE THREAD

**Issue by zxczxc153** [junyiz/dature#19]
![捕获](https://user-images.githubusercontent.com/104623731/188173301-d09f7b18-5419-406c-953c-8e31d2e8737d.PNG)

**Comment by zxczxc153** [comment]
诚恳请求您的帮助

**Comment by zxczxc153** [comment]
用exe文件读取完目录后就卡住了

**Comment by junyiz** [comment]
v1.1.1 修复了此问题
