### ISSUE TITLE
正在抓取… 然后自动停止

### ISSUE THREAD

**Issue by persia7emily** [junyiz/dature#2]
输入命令，正在抓取… 过了一会儿就暂停了，没有生成东西

**Comment by junyiz** [comment]
应该有报错的，把报错信息发出来看看

**Comment by goujibing123** [comment]
我也遇到这个问题，就像是宕机了。
dature -t sina -u 1280592117
这个是我执行的命令，博文：我的西火岁月（28）：小虫的
博文：干板秧歌走京城  在这个地方停止了。

**Comment by junyiz** [comment]
> 我也遇到这个问题，就像是宕机了。
> dature -t sina -u 1280592117
> 这个是我执行的命令，博文：我的西火岁月（28）：小虫的
> 博文：干板秧歌走京城 在这个地方停止了。

我自己试了一下，可以完全抓取的，不会中间停止

**Comment by goujibing123** [comment]
今天早上我抓取完了，我估摸和网络有关系，在网络卡顿的时候。还是非常感谢你开发的这个应用。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月10日 0:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [junyiz/dature] 正在抓取… 然后自动停止 (#2)


我也遇到这个问题，就像是宕机了。
dature -t sina -u 1280592117
这个是我执行的命令，博文：我的西火岁月（28）：小虫的
博文：干板秧歌走京城 在这个地方停止了。

我自己试了一下，可以完全抓取的，不会中间停止

―
