### ISSUE TITLE
博文配图部分丢失

### ISSUE THREAD

**Issue by zxczxc153** [junyiz/dature#20]
尝试了很多次，每次都会丢部分配图，显示不出来，如图所示，希望可以得到解决
谢谢作者开发出这么棒的软件，帮了我们的大忙
![屏幕截图 2022-09-16 184257](https://user-images.githubusercontent.com/104623731/190621747-bb1d1318-4039-41a1-940f-77daf4004886.png)

**Comment by zxczxc153** [comment]
带上cookie后就解决了，真诚感谢作者开的付出

**Comment by zxczxc153** [comment]
包括少量博文配图和部分博客表情

**Comment by junyiz** [comment]
> 包括少量博文配图和部分博客表情

打开对应的新浪博客页面，看看这些图片还能显示吗？

**Comment by zxczxc153** [comment]
> > 包括少量博文配图和部分博客表情
> 
> 打开对应的新浪博客页面，看看这些图片还能显示吗？

可以的，尝试了几次，每次缺失的图片都有所不同

**Comment by junyiz** [comment]
网络不太稳定
