### ISSUE TITLE
抓取报错

### ISSUE THREAD

**Issue by qchenac** [junyiz/dature#3]
范例中抓取牛根生的博客测试没问题，但下面这个博客抓取则会报错
http://blog.sina.com.cn/u/1587015434

报错：`(node:19969) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at Object.extract [as sina] (/usr/local/lib/node_modules/dature/lib/extractor/sina.js:45:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async fetch (/usr/local/lib/node_modules/dature/lib/fetch.js:18:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit **code.`**

**Comment by junyiz** [comment]
已更新，请试试重新抓取

**Comment by qchenac** [comment]
依旧报错...
(node:20476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at Object.extract [as sina] (/usr/local/lib/node_modules/dature/lib/extractor/sina.js:45:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async fetch (/usr/local/lib/node_modules/dature/lib/fetch.js:18:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by junyiz** [comment]
你升级了吗

**Comment by qchenac** [comment]
哦 刚刚更新了 可以了 谢谢您 麻烦了
