### ISSUE TITLE
能不能让程序调用IE的登录状态呀？这样就可以抓取成功了吧。

### ISSUE THREAD

**Issue by mxxba** [junyiz/dature#6]
博客现在不对外开放了，但是作者本人登录后，文章列表什么的都和以前一样。
现在抓取的时候提示抓取成功，0文章。（也就是没有登录状态）
能不能修改一下让程序调用IE的登录状态呀？这样就可以抓取成功了吧。
望百忙之中抽空回复一下。谢谢

**Comment by junyiz** [comment]
已支持
