### ISSUE TITLE
#今天使用发现两点问题，你看是否要优化一下

### ISSUE THREAD

**Issue by redpig315** [junyiz/dature#7]
## 2.部分blog被设置成私密，导致无法取到对应的title和content，这里需要优化一下

总体上工具可用，多谢！

**Comment by junyiz** [comment]
1.  手头没有 windows 机器
2. 有人愿意提供一个有私密文档的账号，就可以优化一下“私密文章”的获取

**Comment by junyiz** [comment]
> ## 1. 使用windows 运行，只能导下一条blog， 但是放在centos上 是没有问题的
> ## 2.部分blog被设置成私密，导致无法取到对应的title和content，这里需要优化一下
> 总体上工具可用，多谢！

1. windows 下，请使用双引号试试，见 [issues#8](https://github.com/junyiz/dature/issues/8#issuecomment-1127144851)
2. 若愿意提供一个有“私密文章”的账号，就可以优化一下对“私密文章”的获取，愿意可发我邮箱 junyime@qq.com
