### ISSUE TITLE
关于cookie的问题

### ISSUE THREAD

**Issue by suckjiba** [junyiz/dature#8]
![sss](https://user-images.githubusercontent.com/39100986/167302343-64ad0ddf-d941-472a-8af0-07d3ebb45215.png)
为什么在这个页面获取到的cookie是这一个呀，与大佬教程的cookie格式不符合。

**Comment by junyiz** [comment]
这个 cookie 看起来没啥问题的，就用这个 cookie 先试试能不能抓？

**Comment by suckjiba** [comment]
> 

不能，提示抓取到了0篇博文。

**Comment by junyiz** [comment]
> 

你重新登录新浪博客，重新拷贝 cookie，再试试

**Comment by junyiz** [comment]
> > 
> 
> 不能，提示抓取到了0篇博文。

 Windows 电脑需要使用双引号，如下，你改成双引号再试试

```bash
# 抓取牛根生的博客
dature -u 1263917762 -c "xxxxxx"

# xxxxxx 为 cookie
```

**Comment by suckjiba** [comment]
> > > 
> > 
> > 
> > 不能，提示抓取到了0篇博文。
> 
> Windows 电脑需要使用双引号，如下，你改成双引号再试试
> 
> ```shell
> # 抓取牛根生的博客
> dature -u 1263917762 -c "xxxxxx"
> 
> # xxxxxx 为 cookie
> ```

哇，可以用了。太感谢大佬啦！谢谢解答！！
