### ISSUE TITLE
读取出的博文篇目数远远超过实际存在的篇目数

### ISSUE THREAD

**Issue by EndlessEnding** [junyiz/dature#9]
提示发现的博文数目是实际篇目的三倍，在每两篇之间都有两个空白。

![图片](https://user-images.githubusercontent.com/61341157/168085476-dbebe4c1-cb5f-4899-99e8-2dd2afa758fd.png)

在全部抓取完后并没有生成 html 文件，只能看到一个 img 文件夹，在抓取过程中也没报错。
![图片](https://user-images.githubusercontent.com/61341157/168085057-7163a15a-72b8-45a6-ab31-be09567a25d7.png)

**Comment by EndlessEnding** [comment]
后续：之前那次是没有把博文抓取完就停止了运行，在多次尝试后，终于有一次把博文全部抓取完了，然后正常生成了 html，但读取数目是博文数三倍的问题依然存在。

**Comment by junyiz** [comment]
生成的 html 里包含的博文数目对吗？

**Comment by EndlessEnding** [comment]
> 生成的 html 里包含的博文数目对吗？

是对的

**Comment by junyiz** [comment]
> > 生成的 html 里包含的博文数目对吗？
> 
> 是对的

抓取过程，有点瑕疵，我知道的

**Comment by junyiz** [comment]
这个瑕疵已经修复了

**Comment by EndlessEnding** [comment]
> 这个瑕疵已经修复了

好，谢谢您！
